-
  branches:
    only:
      - master

  os: Visual Studio 2017

  configuration: 
    - debug
    - release

  environment:
    SKIP_NODE_ODBC_BINARY_DOWNLOAD_ON_CI: 1
    NODE_ODBC_TEST_USE_APPVEYOR_CONFIG: 1


  services:
    - mssql2016
    - mysql
    - postgresql

  platform:
    - x64
    - x86

  version: "{build}"


  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      - nodejs_version: 6
        GYP_MSVS_VERSION: 2017
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017



  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - node --version
    - npm --version
    - npm install
    - cmd: SET PATH=%cd%\node_modules\.bin\;%PATH%
    - cmd: typings install
  
  build_script:
    - cmd: tsc -p dist
    - cmd: tsc -p test
    - cmd: node-gyp configure
    - cmd: node-gyp build

  on_success:
    - npm run test