-
  branches:
    only:
      - master

  os: Visual Studio 2015

  configuration: release

  services:
    - mssql2016
#    - mysql
#    - postgresql

  platform:
    - x64
    - x86

  version: "{build}"

  build: off

  clone_folder: c:\projects\node_modules\node-odbc

  init:
    - cmd: >-
        subst s: c:\projects
    - ps: set-location -path s:\node_modules\node-odbc

  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    SKIP_NODE_ODBC_BINARY_DOWNLOAD_ON_CI: true
    NODE_ODBC_TEST_USE_APPVEYOR_CONFIG: true

    matrix:
      - nodejs_version: 6
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - nodejs_version: 7
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
      - nodejs_version: 8
        GYP_MSVS_VERSION: 2015
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015


  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - node --version
    - npm --version
    - npm install
    - cmd: SET PATH=%cd%\node_modules\.bin\;%PATH%
    - cmd: typings install
  
  build_script:
    - cmd: tsc -p lib
    - cmd: tsc -p test
    - cmd: tsc -p scripts
    - npm run build

  test: off
  
  test_script:
    - npm run test

  before_deploy:
    - ps: >-
        Get-ChildItem .\vendor\**\*.node | % {
           ( $BindingName = $_.FullName ).Split('\\') |
             Select-Object -Last 2 | Select-Object -First 1 } |
               .{ process { (
                  @( $BindingName,
                       ( ( $_, "node-odbc.node" ) -join '_' ) ),
                  @( ".\build\Release\node-odbc.pdb", ( ( $_, "node-odbc.pdb" ) -join '_' ) )
               ) } } | % { Push-AppveyorArtifact $_[0] -FileName $_[1] }

  deploy:
    - provider: GitHub
      description: $(APPVEYOR_REPO_COMMIT_MESSAGE_EXTENDED)
      artifact:
      auth_token:
        secure: 3nVOtEyNM2nI0/3mVltASP4rtBfLXWLYeqfjRfnIITF+AyT6gKf99JsaPiNERx4f
      on:
        appveyor_repo_tag: true       # deploy on tag push only