-
  branches:
    only:
      - master

  os: Visual Studio 2017

  configuration: release

  platform:
    - x64
    - x86

  version: "{build}"


  cache:
    - '%userprofile%\.node-gyp'
    - '%AppData%\npm-cache'

  environment:
    SKIP_SASS_BINARY_DOWNLOAD_FOR_CI: true
    matrix:
      - nodejs_version: 6
        GYP_MSVS_VERSION: 2017
        APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017



  install:
    - ps: Install-Product node $env:nodejs_version $env:platform
    - ps: Get-Location
    - node --version
    - npm --version
    - cmd: dir
